#This is the default config for [DeathCharge]

#Determines if the value chosen to be taken
#is either a percentage or a hard amount
isPercent: true

#If isPercent is false, and a player does not
#have sufficient funds to pay the deathcharge,
#drain will determine whether to drain the
#remaining funds and reset their balance to $0
#or leave their balance alone
drain: false

#Percent/Amount to be taken on death
# EXAMPLE:
#        |=======================================|
#        |amountTaken: 5.00                      |
#        |isPercent: true                        |
#        |Players lose 5% of their money on death|
#        |=======================================|
#        |amountTaken: 5.00                      |
#        |isPercent: false                       |
#        |Players lose $5 of their money on death|
#        |=======================================|
amountTaken: 5.00

#PVP determines if death charge is invoked
#on deaths caused by pvp
# false = will lose money on pvp
# true = will not lose money on pvp
pvp: false

#Message determines what message will be sent
#to the player upon death. All standard color
#codes are supported and all messages will
#start with [DeathCharge]
#
# {MONEY} = amount lost on death
message: "&cYou have lost &a{MONEY}&c on death!"