name: DeathCharge
main: com.github.seemethere.DeathCharge.DeathCharge
version: 1.5
author: seemethere
depend: [Vault, WorldGuard, WorldEdit]
commands:
    deathcharge:
        description: Generic base command for DeathCharge
        usage: /<command> args
